name: deploy frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t abhisharma811/test-docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true abhisharma811/test-docker-react npm test
