name: deploy frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t abhisharma811/test-docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true abhisharma811/test-docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x \*.git\*

      - name: Deploy to Elastic beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          enviroment: Frontend-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-471112596323
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
